version: "2"

formatters:
  enable:
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
